### PR TITLE
Only clear scale cache if image has changed

### PR DESCRIPTION
**Pull request by hedleyroos**
The clear_cache method is called every time an ImageModel is saved. This has the side effect of removing scaled images from storage. When run behind a reverse caching proxy the calls to eg. get_image_url are not made on every request, thus the scale is not recreated, resulting in a 404 for the image on the web page.

This simple check fixes it. Initially I thought I would have to compare file contents but this is much simpler.

### CODE REVIEW

**Comment by richardbarran** [comment]
Hi,
I am currently in the middle of a house move - so rather busy! Might be a few weeks before I can take a look at this, but I *will* look into it.

**Comment by hedleyroos** [comment]
Hi Richard. Have you moved house yet? :)

**Comment by richardbarran** [comment]
I've moved, but I'm still catching up on work/life. Will get back onto Photologue in a few more weeks.

**Comment by richardbarran** [comment]
Hi,
Thanks for the contrib! And my apologies for the delay in merging it.

**Pull request merged**
